### ISSUE TITLE
Change test ReadPlanFile function

### ISSUE THREAD

**Issue by thiagonache** [thiagonache/terraformtest#4]
Depends on https://github.com/thiagonache/terraformtest/issues/3.

The test function ReadPlanFile should Fatal instead of Error since nothing can be done if it cannot read the file.

Also, we should update from `wantBiggerThan := 2000` to `want := the exact number of bytes`.

**Comment by apitta** [comment]
#6 renames the variable and fails in case terraformtest can't read the file
